---
- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: rabbitmq-server-test
    release: cf-rabbitmq

- type: replace
  path: /properties/rabbitmq-server-test?
  value:
    use_native_clustering_formation: ((use-native-clustering-formation))
