- type: replace
  path: /instance_groups/name=rmq/properties?
  value:
    syslog_aggregator:
      address: ((syslog-host))
      port: ((syslog-port))

- type: replace
  path: /instance_groups/name=haproxy/properties?
  value:
    syslog_aggregator:
      address: ((syslog-host))
      port: ((syslog-port))
