---
name: ((deployment-name))
director_uuid: ((director-uuid))

releases:
- name: cf-rabbitmq
  version: latest
- name: cf-rabbitmq-multitenant-broker
  version: latest
- name: routing
  version: 0.152.0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.152.0
  sha1: ea67ad087880fc0e492b6cce27fa2a25f977b691

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

instance_groups:
- name: rmq
  instances: 3
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
  vm_type: r3.xlarge
  stemcell: trusty
  persistent_disk_type: 100GB
  networks:
  - name: services
  azs:
  - eu-west-1a
  - eu-west-1b

- name: rmq-broker
  instances: 1
  jobs:
  - name: rabbitmq-broker
    release: cf-rabbitmq-multitenant-broker
  - name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: cf}
    properties:
      route_registrar:
        routes:
        - name: ((rabbitmq-broker-domain))
          port: 4567
          registration_interval: 20s
          uris:
          - ((rabbitmq-broker-domain)).((bosh-hostname))
  vm_type: m3.medium
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: haproxy
  instances: ((haproxy-instances))
  jobs:
  - name: rabbitmq-haproxy
    release: cf-rabbitmq
  - name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: cf}
    properties:
      route_registrar:
        routes:
        - name: ((rabbitmq-management-domain))
          port: 15672
          registration_interval: 20s
          uris:
          - ((rabbitmq-management-domain)).((bosh-hostname))
  vm_type: m3.medium
  stemcell: trusty
  networks:
  - name: services
  azs:
  - eu-west-1a
  - eu-west-1b

- name: broker-registrar
  jobs:
  - name: broker-registrar
    release: cf-rabbitmq-multitenant-broker
  instances: 1
  lifecycle: errand
  vm_type: f1-micro
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: broker-deregistrar
  jobs:
  - name: broker-deregistrar
    release: cf-rabbitmq-multitenant-broker
  instances: 1
  lifecycle: errand
  vm_type: f1-micro
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: smoke-tests
  jobs:
  - name: smoke-tests
    release: cf-rabbitmq-multitenant-broker
    consumes:
      cloud_controller: {from: cloud_controller, deployment: cf}
  instances: 1
  lifecycle: errand
  vm_type: m3.medium
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

properties:
  cf:
    admin_username: ((cf-admin-username))
    admin_password: ((cf-admin-password))
    api_url: http://api.((bosh-hostname))

  broker:
    host: ((rabbitmq-broker-domain)).((bosh-hostname))
    protocol: ((rabbitmq-broker-protocol))
    name: ((product-name))
    username: ((multitenant-rabbitmq-broker-username))
    password: ((multitenant-rabbitmq-broker-password))
    service:
      name: ((product-name))

  rabbitmq-server:
    plugins:
    - rabbitmq_management
    - rabbitmq_mqtt
    - rabbitmq_stomp
    ports:
    - 5672
    - 5671
    - 1883
    - 8883
    - 61613
    - 61614
    - 15672
    - 15674
    administrators:
      management:
        username: ((rabbitmq-management-username))
        password: ((rabbitmq-management-password))
      broker:
        username: ((rabbitmq-broker-username))
        password: ((rabbitmq-broker-password))
    cookie: "rabbit-cluster:aws"
    cluster_partition_handling: ((cluster-partition-handling-strategy))

  rabbitmq-haproxy:
    stats:
      username: ((haproxy-stats-username))
      password: ((haproxy-stats-password))

  rabbitmq-broker:
    route: ((rabbitmq-broker-domain))
    cc_endpoint: http://api.((bosh-hostname))
    service:
      username: ((multitenant-rabbitmq-broker-username))
      password: ((multitenant-rabbitmq-broker-password))
      name: ((product-name))
      uuid: ((rabbitmq-broker-uuid))
      plan_uuid: ((rabbitmq-broker-plan-uuid))
    logging:
      level: debug
      print_stack_traces: false
    rabbitmq:
      hosts: ((rabbitmq-hosts))
      operator_set_policy:
        enabled: true
        policy_name: "operator_set_policy"
        policy_definition: "{\"ha-mode\":\"exactly\",\"ha-params\":2,\"ha-sync-mode\":\"automatic\"}"
        policy_priority: 50
      management_domain: ((rabbitmq-management-domain)).((bosh-hostname))
      ssl: false
      administrator:
        username: ((rabbitmq-broker-username))
        password: ((rabbitmq-broker-password))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false
