---
name: ((deployment-name))
director_uuid: ((director-uuid))

releases:
- name: ((cf-rabbitmq-release-name))
  version: latest
- name: syslog-migration
  version: 3

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

instance_groups:
- name: rmq
  instances: 3
  jobs:
  - name: rabbitmq-server
    release: ((cf-rabbitmq-release-name))
  - name: syslog_forwarder
    release: syslog-migration
  vm_type: r3.large
  stemcell: trusty
  persistent_disk_type: 10GB
  networks:
  - name: services
  azs:
  - eu-west-1a
  - eu-west-1b

- name: haproxy
  instances: ((haproxy-instances))
  jobs:
  - name: rabbitmq-haproxy
    release: ((cf-rabbitmq-release-name))
  vm_type: m3.medium
  stemcell: trusty
  networks:
  - name: services
  azs:
  - eu-west-1a
  - eu-west-1b

properties:
  syslog:
    migration:
      message_format: job_index_id
    address: ((syslog-aggregator-address))
    port: ((syslog-aggregator-port))
    custom_rule: |
      module(load="imfile")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/rabbit@*.log"
            Tag="rabbitmq")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/rabbit@*-sasl.log"
            Tag="rabbitmq_sasl")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/startup_stderr.log"
            Tag="rabbitmq_startup_stderr")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/startup_stdout.log"
            Tag="rabbitmq_startup_stdout")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/shutdown_stdout.log"
            Tag="rabbitmq_shutdown_stdout")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/shutdown_stderr.log"
            Tag="rabbitmq_shutdown_stderr")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/management-ui/access.log*"
            Tag="rabbitmq_http_api_access")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/upgrade.log"
            Tag="rabbitmq_upgrade")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/init.log"
            Tag="rabbitmq_init")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/node-check.log"
            Tag="rabbitmq_node_check")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/cluster-check.log"
            Tag="rabbitmq_cluster_check")

      input(type="imfile"
            File="/var/vcap/sys/log/rabbitmq-server/pre-start.log"
            Tag="rmq_server_pre_start")
  rabbitmq-server:
    restart_statsdb_cron_schedule: "42 */4 * * *"
    plugins:
    - rabbitmq_management
    - rabbitmq_mqtt
    - rabbitmq_stomp
    ports:
    - 5672
    - 5671
    - 1883
    - 8883
    - 61613
    - 61614
    - 15672
    - 15674
    administrators:
      management:
        username: ((rabbitmq-management-username))
        password: ((rabbitmq-management-password))
      broker:
        username: ((rabbitmq-broker-username))
        password: ((rabbitmq-broker-password))
    cookie: "rabbit-cluster:aws"
    cluster_partition_handling: autoheal

  rabbitmq-haproxy:
    stats:
      username: ((haproxy-stats-username))
      password: ((haproxy-stats-password))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
