---
deployment-name: cf-rabbitmq

stemcell-version: '3421.20'

haproxy-instances: 2

rabbitmq-management-username: admin
rabbitmq-management-password: admin

rabbitmq-broker-username: broker
rabbitmq-broker-password: broker

haproxy-stats-username: haproxy
haproxy-stats-password: haproxy

use-native-clustering-formation: true

cluster-partition-handling-strategy: autoheal

syslog-host:
syslog-port:

cf-admin-password: admin
cf-admin-username: admin
