---
deployment-name: cf-rabbitmq

stemcell-version: 3421.24

haproxy-instances: 1
haproxy-ips: [10.244.16.3]

rabbitmq-management-username: admin
rabbitmq-management-password: admin

rabbitmq-broker-username: broker
rabbitmq-broker-password: broker

haproxy-stats-username: haproxy
haproxy-stats-password: haproxy

use-native-clustering-formation: false

cluster-partition-handling-strategy: autoheal

syslog-host:
syslog-port:

cf-admin-password: admin
cf-admin-username: admin
